/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculator;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Acer
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    
    double NumEnter1;
    double NumEnter2;
    double Result;
    String op;
    public Calculator() {
    initComponents();
    Image icon = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Acer\\OneDrive\\Pictures\\8159145.png");
    this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtResult = new javax.swing.JTextField();
        jbtnPM = new javax.swing.JButton();
        jbtnbackSp = new javax.swing.JButton();
        jbtnCE = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtnDigit7 = new javax.swing.JButton();
        jbtnDigit8 = new javax.swing.JButton();
        jbtnDigit9 = new javax.swing.JButton();
        jbtnPlus = new javax.swing.JButton();
        jbtnDigit4 = new javax.swing.JButton();
        jbtnDigit5 = new javax.swing.JButton();
        jbtnDigit6 = new javax.swing.JButton();
        jbtnMinus = new javax.swing.JButton();
        jbtnMultiple = new javax.swing.JButton();
        jbtnDigit3 = new javax.swing.JButton();
        jbtnDigit2 = new javax.swing.JButton();
        jbtnDigit1 = new javax.swing.JButton();
        jbtnDigit0 = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jbtnDivide = new javax.swing.JButton();
        jbtnEqual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtResult.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        jtxtResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jtxtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 310, 60));

        jbtnPM.setBackground(new java.awt.Color(255, 204, 0));
        jbtnPM.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jbtnPM.setText("±");
        jbtnPM.setPreferredSize(new java.awt.Dimension(72, 7));
        jbtnPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPMActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, 70));

        jbtnbackSp.setBackground(new java.awt.Color(255, 204, 0));
        jbtnbackSp.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jbtnbackSp.setText("<---");
        jbtnbackSp.setPreferredSize(new java.awt.Dimension(72, 7));
        jbtnbackSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbackSpActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnbackSp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 70));

        jbtnCE.setBackground(new java.awt.Color(255, 204, 0));
        jbtnCE.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jbtnCE.setText("CE");
        jbtnCE.setPreferredSize(new java.awt.Dimension(72, 7));
        jbtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCEActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 70));

        jbtnC.setBackground(new java.awt.Color(255, 204, 0));
        jbtnC.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jbtnC.setText("C");
        jbtnC.setPreferredSize(new java.awt.Dimension(72, 7));
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, 70));

        jbtnDigit7.setBackground(new java.awt.Color(0, 102, 204));
        jbtnDigit7.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jbtnDigit7.setText("7");
        jbtnDigit7.setPreferredSize(new java.awt.Dimension(72, 7));
        jbtnDigit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit7ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 70));

        jbtnDigit8.setBackground(new java.awt.Color(0, 102, 204));
        jbtnDigit8.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jbtnDigit8.setText("8");
        jbtnDigit8.setMaximumSize(new java.awt.Dimension(72, 7));
        jbtnDigit8.setMinimumSize(new java.awt.Dimension(72, 7));
        jbtnDigit8.setPreferredSize(new java.awt.Dimension(72, 7));
        jbtnDigit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit8ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, 70));

        jbtnDigit9.setBackground(new java.awt.Color(0, 102, 204));
        jbtnDigit9.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jbtnDigit9.setText("9");
        jbtnDigit9.setPreferredSize(new java.awt.Dimension(72, 7));
        jbtnDigit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit9ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigit9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, 70));

        jbtnPlus.setBackground(new java.awt.Color(255, 204, 0));
        jbtnPlus.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jbtnPlus.setText("+");
        jbtnPlus.setPreferredSize(new java.awt.Dimension(72, 7));
        jbtnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPlusActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, 70));

        jbtnDigit4.setBackground(new java.awt.Color(0, 102, 204));
        jbtnDigit4.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jbtnDigit4.setText("4");
        jbtnDigit4.setPreferredSize(new java.awt.Dimension(72, 7));
        jbtnDigit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit4ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 70));

        jbtnDigit5.setBackground(new java.awt.Color(0, 102, 204));
        jbtnDigit5.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jbtnDigit5.setText("5");
        jbtnDigit5.setPreferredSize(new java.awt.Dimension(72, 7));
        jbtnDigit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit5ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, 70));

        jbtnDigit6.setBackground(new java.awt.Color(0, 102, 204));
        jbtnDigit6.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jbtnDigit6.setText("6");
        jbtnDigit6.setPreferredSize(new java.awt.Dimension(72, 7));
        jbtnDigit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit6ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, 70));

        jbtnMinus.setBackground(new java.awt.Color(255, 204, 0));
        jbtnMinus.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jbtnMinus.setText("-");
        jbtnMinus.setPreferredSize(new java.awt.Dimension(72, 7));
        jbtnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMinusActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, 70));

        jbtnMultiple.setBackground(new java.awt.Color(255, 204, 0));
        jbtnMultiple.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jbtnMultiple.setText("x");
        jbtnMultiple.setPreferredSize(new java.awt.Dimension(72, 7));
        jbtnMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMultipleActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnMultiple, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, 70));

        jbtnDigit3.setBackground(new java.awt.Color(0, 102, 204));
        jbtnDigit3.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jbtnDigit3.setText("3");
        jbtnDigit3.setPreferredSize(new java.awt.Dimension(72, 7));
        jbtnDigit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, 70));

        jbtnDigit2.setBackground(new java.awt.Color(0, 102, 204));
        jbtnDigit2.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jbtnDigit2.setText("2");
        jbtnDigit2.setPreferredSize(new java.awt.Dimension(72, 7));
        jbtnDigit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, 70));

        jbtnDigit1.setBackground(new java.awt.Color(0, 102, 204));
        jbtnDigit1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jbtnDigit1.setText("1");
        jbtnDigit1.setPreferredSize(new java.awt.Dimension(72, 7));
        jbtnDigit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 70));

        jbtnDigit0.setBackground(new java.awt.Color(0, 102, 204));
        jbtnDigit0.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jbtnDigit0.setText("0");
        jbtnDigit0.setPreferredSize(new java.awt.Dimension(72, 7));
        jbtnDigit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit0ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDigit0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 70));

        jbtnDot.setBackground(new java.awt.Color(255, 204, 0));
        jbtnDot.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.setPreferredSize(new java.awt.Dimension(72, 7));
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, 70));

        jbtnDivide.setBackground(new java.awt.Color(255, 204, 0));
        jbtnDivide.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jbtnDivide.setText("÷");
        jbtnDivide.setPreferredSize(new java.awt.Dimension(72, 7));
        jbtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDivideActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, 70));

        jbtnEqual.setBackground(new java.awt.Color(255, 204, 0));
        jbtnEqual.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jbtnEqual.setText("=");
        jbtnEqual.setPreferredSize(new java.awt.Dimension(72, 7));
        jbtnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEqualActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterNumbers(String q)
    {
        String Nums = jtxtResult.getText() + q;
        jtxtResult.setText(Nums);
    }
    
    private void jbtnbackSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackSpActionPerformed
        
        String backSp = null;
        
        if (jtxtResult.getText().length() > 0)
        {
            StringBuilder sb = new StringBuilder(jtxtResult.getText());
            sb.deleteCharAt(jtxtResult.getText().length() -1);
            backSp = sb.toString();
            jtxtResult.setText(backSp);
        }
    }//GEN-LAST:event_jbtnbackSpActionPerformed

    private void jbtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCEActionPerformed
        jtxtResult.setText("");
        
        String Fn, Sn;
        
        Fn = String.valueOf(NumEnter1);
        Sn = String.valueOf(NumEnter2);
        
        Fn =""; 
        Sn ="";
        
    }//GEN-LAST:event_jbtnCEActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        jtxtResult.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtnDigit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit7ActionPerformed
        
        EnterNumbers("7");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDigit7ActionPerformed

    private void jbtnDigit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit8ActionPerformed
        
        EnterNumbers("8");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDigit8ActionPerformed

    private void jbtnDigit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit9ActionPerformed

        EnterNumbers("9");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDigit9ActionPerformed

    private void jbtnDigit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit4ActionPerformed

        EnterNumbers("4");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDigit4ActionPerformed

    private void jbtnDigit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit5ActionPerformed

        EnterNumbers("5");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDigit5ActionPerformed

    private void jbtnDigit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit6ActionPerformed

        EnterNumbers("6");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDigit6ActionPerformed

    private void jbtnDigit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit3ActionPerformed

        EnterNumbers("3");

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDigit3ActionPerformed

    private void jbtnDigit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit2ActionPerformed

        EnterNumbers("2");

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDigit2ActionPerformed

    private void jbtnDigit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit1ActionPerformed

        EnterNumbers("1");

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDigit1ActionPerformed

    private void jbtnDigit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit0ActionPerformed


        EnterNumbers("0");

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDigit0ActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
        
        if (! jtxtResult.getText().contains("."))
        {
            jtxtResult.setText(jbtnDot + jbtnDot.getText());
        }
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEqualActionPerformed
        
        NumEnter2 = Double.parseDouble(jtxtResult.getText());
        String equation = NumEnter1 + " " + op + " " + NumEnter2 + " = ";
        if (op == "+")
        {
            Result = NumEnter1 + NumEnter2;
            jtxtResult.setText(equation + String.valueOf(Result));
        }
        
        else if (op == "-")
        {
            Result = NumEnter1 - NumEnter2;
            jtxtResult.setText(equation + String.valueOf(Result));
        }
        
        else if (op == "x")
        {
            Result = NumEnter1 * NumEnter2;
            jtxtResult.setText(equation + String.valueOf(Result));
        }
        
        else if (op == "÷")
        {
            Result = NumEnter1 / NumEnter2;
            jtxtResult.setText(equation + String.valueOf(Result));
        }
    }//GEN-LAST:event_jbtnEqualActionPerformed

    private void jbtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDivideActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        op = "÷"; 
    }//GEN-LAST:event_jbtnDivideActionPerformed

    private void jbtnMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultipleActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        op = "x"; 
    }//GEN-LAST:event_jbtnMultipleActionPerformed

    private void jbtnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMinusActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        op = "-";
    }//GEN-LAST:event_jbtnMinusActionPerformed

    private void jbtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPlusActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        op = "+";
    }//GEN-LAST:event_jbtnPlusActionPerformed

    private void jbtnPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPMActionPerformed
        
        double nums = Double.parseDouble(String.valueOf(jtxtResult.getText()));
        nums = nums * (-1);
        jtxtResult.setText(String.valueOf(nums));
    }//GEN-LAST:event_jbtnPMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnCE;
    private javax.swing.JButton jbtnDigit0;
    private javax.swing.JButton jbtnDigit1;
    private javax.swing.JButton jbtnDigit2;
    private javax.swing.JButton jbtnDigit3;
    private javax.swing.JButton jbtnDigit4;
    private javax.swing.JButton jbtnDigit5;
    private javax.swing.JButton jbtnDigit6;
    private javax.swing.JButton jbtnDigit7;
    private javax.swing.JButton jbtnDigit8;
    private javax.swing.JButton jbtnDigit9;
    private javax.swing.JButton jbtnDivide;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnEqual;
    private javax.swing.JButton jbtnMinus;
    private javax.swing.JButton jbtnMultiple;
    private javax.swing.JButton jbtnPM;
    private javax.swing.JButton jbtnPlus;
    private javax.swing.JButton jbtnbackSp;
    private javax.swing.JTextField jtxtResult;
    // End of variables declaration//GEN-END:variables
}
